apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: {{ cookiecutter.namespace }}
  labels:
    app: redis
spec:
  ports:
  - name: "6379tcp"
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
