apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: {{ cookiecutter.namespace }}
  labels:
    app: web
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: web
