apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ cookiecutter.namespace }}-gw
  namespace: {{ cookiecutter.namespace }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http80
      protocol: HTTP
    hosts:
      - '*'