all:
	docker pull nginx:1.21.6
	docker tag nginx:1.21.6 registry.sb.upf.edu/mtg/nginx:1.21.6
	docker push registry.sb.upf.edu/mtg/nginx:1.21.6

	docker pull redis:6.2.5
	docker tag redis:6.2.5 registry.sb.upf.edu/mtg/redis:6.2.5
	docker push registry.sb.upf.edu/mtg/redis:6.2.5